# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Infra&Security Services Blog
email:
description: >-
  As the world becomes increasingly connected, the need for strong cybersecurity measures becomes more important than ever. 
  From individual users to large organizations, everyone is at risk of cyber attacks, and it's essential to take steps to protect yourself and your information.
  In this blog, we'll explore the various aspects of cybersecurity and provide tips and advice on how to stay safe online. 
  From choosing secure passwords to understanding the latest threats, we'll help you stay one step ahead of the bad guys and keep your information safe.
twitter_username: infracybersec
github_username: infracybersec
minimal_mistakes_skin: air
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: FR

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Infra&Security Services"
  avatar : "/assets/images/shield.png"
  bio    : "Cybersecurity Consulting, Cloud Infrastructure"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://infrasecurityservices.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/infracybersec"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/infracybersec"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/infracybersec"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/infracybersec"


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
